name: Publish Python Package
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/kataCheckout@v2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine bump2version

    - name: Bump version and build package
      run: |
        bump2version patch  # Can be 'patch', 'minor', or 'major'
        python setup.py sdist bdist_wheel

    - name: Run tests
      run: |
        pip install -r requirements.txt
        python -m unittest discover -s tests

    - name: Publish package to PyPI
      if: github.ref == 'refs/heads/main'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m twine upload dist/*